# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 19:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=b'default', max_length=30)),
                ('firstname', models.CharField(default=b'default', max_length=20)),
                ('lastname', models.CharField(default=b'default', max_length=40)),
                ('email', models.EmailField(default=b'default@gmail.com', max_length=50)),
                ('birth', models.DateField(default=datetime.date.today, verbose_name=b'Birth Date')),
                ('phone', models.CharField(default=b'(111) 111-1111', max_length=20)),
                ('address', models.CharField(default=b'111 11th Avenue, New York, NY 10001', max_length=50)),
                ('prefered', models.CharField(default=b'none selected', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=b'default', max_length=30)),
                ('firstname', models.CharField(default=b'default', max_length=20)),
                ('lastname', models.CharField(default=b'default', max_length=40)),
                ('email', models.EmailField(default=b'default@gmail.com', max_length=50)),
                ('degree', models.CharField(default=b'Ph.D.', max_length=200)),
                ('profession', models.CharField(default=b'Surgeon', max_length=200)),
                ('birth', models.DateField(default=datetime.date.today, verbose_name=b'Birth Date')),
                ('phone', models.CharField(default=b'(111) 111-1111', max_length=20)),
                ('address', models.CharField(default=b'111 11th Avenue, New York, NY 10001', max_length=50)),
                ('prefered', models.CharField(default=b'none selected', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=b'1111-01-01')),
                ('time', models.CharField(default=b'8am', max_length=4)),
                ('owner', models.CharField(default=b'default', max_length=30)),
                ('doctor', models.CharField(default=b'must select', max_length=40)),
                ('reason', models.TextField(blank=True, default=b'must add reason for visit', max_length=10000)),
                ('approved', models.BooleanField(default=False)),
                ('cancel', models.BooleanField(default=False)),
                ('submitted', models.BooleanField(default=False)),
                ('idtag', models.CharField(default=b'must select', max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=100)),
                ('address', models.CharField(default=b'', max_length=100)),
                ('phone', models.CharField(default=b'', max_length=100)),
                ('email', models.EmailField(default=b'default@gmail.com', max_length=50)),
                ('hours', models.CharField(default=b'', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default=b'default', max_length=30)),
                ('username', models.CharField(default=b'default', max_length=30)),
                ('event_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManagerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=b'default', max_length=30)),
                ('firstname', models.CharField(default=b'default', max_length=20)),
                ('lastname', models.CharField(default=b'default', max_length=40)),
                ('email', models.EmailField(default=b'default@gmail.com', max_length=50)),
                ('birth', models.DateField(default=datetime.date.today, verbose_name=b'Birth Date')),
                ('phone', models.CharField(default=b'(111) 111-1111', max_length=20)),
                ('address', models.CharField(default=b'111 11th Avenue, New York, NY 10001', max_length=50)),
                ('prefered', models.CharField(default=b'none selected', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=b'default', max_length=30)),
                ('emergency', models.CharField(default=b'(222) 222-2222', max_length=50)),
                ('ssn', models.CharField(default=b'111-11-1111', max_length=11)),
                ('insurance', models.CharField(default=b'11-111-1111-1', max_length=20)),
                ('provider', models.CharField(default=b'MedCorp Inc.', max_length=20)),
                ('conditions', models.TextField(blank=True, default=b'', max_length=10000)),
                ('perscriptions', models.TextField(blank=True, default=b'', max_length=10000)),
                ('results', models.TextField(blank=True, default=b'', max_length=10000)),
                ('currenthospital', models.CharField(default=b'none', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default=b'', max_length=500)),
                ('sender', models.CharField(default=b'default', max_length=30)),
                ('reciever', models.CharField(default=b'default', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='NurseProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=b'default', max_length=30)),
                ('firstname', models.CharField(default=b'default', max_length=20)),
                ('lastname', models.CharField(default=b'default', max_length=40)),
                ('email', models.EmailField(default=b'default@gmail.com', max_length=50)),
                ('birth', models.DateField(default=datetime.date.today, verbose_name=b'Birth Date')),
                ('phone', models.CharField(default=b'(111) 111-1111', max_length=20)),
                ('address', models.CharField(default=b'111 11th Avenue, New York, NY 10001', max_length=50)),
                ('prefered', models.CharField(default=b'none selected', max_length=20)),
                ('workhospital', models.CharField(default=b'none selected', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=b'default', max_length=30)),
                ('firstname', models.CharField(default=b'default', max_length=20)),
                ('lastname', models.CharField(default=b'default', max_length=40)),
                ('email', models.EmailField(default=b'default@gmail.com', max_length=50)),
                ('phone', models.CharField(default=b'(111) 111-1111', max_length=20)),
                ('birth', models.DateField(default=datetime.date.today, verbose_name=b'Birth Date')),
                ('address', models.CharField(default=b'111 11th Avenue, New York, NY 10001', max_length=50)),
                ('prefered', models.CharField(default=b'none selected', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SecretaryProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=b'default', max_length=30)),
                ('firstname', models.CharField(default=b'default', max_length=20)),
                ('lastname', models.CharField(default=b'default', max_length=40)),
                ('email', models.EmailField(default=b'default@gmail.com', max_length=50)),
                ('birth', models.DateField(default=datetime.date.today, verbose_name=b'Birth Date')),
                ('phone', models.CharField(default=b'(111) 111-1111', max_length=20)),
                ('address', models.CharField(default=b'111 11th Avenue, New York, NY 10001', max_length=50)),
                ('prefered', models.CharField(default=b'none selected', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=b'default', max_length=30)),
                ('type', models.CharField(default=b'', max_length=20)),
                ('patient', models.BooleanField(default=False)),
            ],
        ),
    ]
